[package]
name = "cas_session"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
cas_ast = { path = "../cas_ast" }

[dev-dependencies]
cas_parser = { path = "../cas_parser" }
