[workspace]
members = [
    "crates/cas_ast",
    "crates/cas_engine",
    "crates/cas_parser",
    "crates/cas_format",
    "crates/cas_cli",
]
resolver = "2"
[workspace.package]
license = "MIT"
authors = ["Javier Gimenez Moya"]
