[workspace]
members = [
    "crates/cas_ast",
    "crates/cas_engine",
    "crates/cas_parser",
    "crates/cas_format",
    "crates/cas_cli",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.88"
license = "MIT"
authors = ["Javier Gimenez Moya"]

