[package]
name = "cas_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cas_ast = { path = "../cas_ast" }
cas_parser = { path = "../cas_parser" }
cas_engine = { path = "../cas_engine" }
rustyline = "12.0"
num-traits = "0.2"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
