[package]
name = "cas_solver"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["parallel"]
parallel = ["cas_engine/parallel"]

[dependencies]
cas_engine = { path = "../cas_engine", default-features = false }
